apiVersion: apps/v1
kind: Deployment
metadata:
  name: attache-sidecar
  labels:
    app: attache-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attache-sidecar
  template:
    metadata:
      labels:
        app: attache-sidecar
    spec:
      containers:
        - name: attache-sidecar
          image: downfa11/attache:latest
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
