global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "solve-metrics"
    scheme: https
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "api.hpground.xyz443"
    tls_config:
      insecure_skip_verify: true
