global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "solve-metrics"
    scheme: https
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "ec2-3-34-134-27.ap-northeast-2.compute.amazonaws.com:443"
    tls_config:
      insecure_skip_verify: true
