name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths-ignore:
          - 'README.md'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes excluding README.md
        id: changes
        run: |
          git fetch origin master
          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -v '^README\.md$' || true)
          if [ -z "$FILES_CHANGED" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel job if only README.md changed
        if: steps.changes.outputs.no_changes == 'true'
        run: |
          echo "Only README.md changed. Skipping deployment."
          exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solve:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/solve:latest
            docker compose down
            docker compose up -d --remove-orphans
