name: KOREN GitOps Pipeline (ArgoCD)

on:
  push:
    branches:
      - koren

jobs:
  membership:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build JAR with Gradle
        run: ./gradlew bootJar

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: hpg
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile.koren .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Checkout Helm Repository
        uses: actions/checkout@v3
        with:
          repository: downfa11/k8s-Devops
          path: k8s-Devops
          ref: koren
          ssh-key: ${{ secrets.HELM_CHARTS_REPO_KEY }}

      - name: Change Image tag of the Helm value
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq -i '.image.tag = "${{ env.IMAGE_TAG }}"' k8s-Devops/hpg-chart/backend-chart/values-koren.yaml

      - name: Commit and Push HELM changes
        run: |
          cd k8s-Devops
          git config --local user.email "downfa11@naver.com"
          git config --local user.name "downfa11"
          git add .
          git commit -m "Automated update: hpg image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push origin koren
